# Chapter 5: MISC.

The goal of this chapter is to gain insights in multiple things that you might encounter in your work but also that you will probably learn more about in other course.

I already talked about the way I do my work by combining both Python and R. Other Business Analytics tools exists and are popular in companies. I really suggest to look into it and try to integrate them in your workflow. To get started with the different softwares and see how it works we will use data from the UCI Machine Learning repository https://archive.ics.uci.edu/dataset/116/us+census+data+1990.

- [Pytorch and Keras](#Pytorch)
- [Power BI](#PowerBI)
- [Previous Project](#PreviousProject)

<a name="Pytorch"></a>
## Pytorch and Keras

This section will introduce two of the prominent machine learning library: Pytorch and Keras.

PyTorch is an open-source machine learning library developed by Facebook's AI Research lab (FAIR). It has gained popularity for its flexibility, dynamic computational graph, and ease of use. PyTorch is widely used for deep learning applications, including neural network development, natural language processing, computer vision, and more. At the core of PyTorch is the tensor, which is a multi-dimensional array similar to NumPy arrays. Tensors can represent scalars, vectors, matrices, and higher-dimensional arrays. PyTorch provides a variety of tensor operations that make it easy to perform mathematical computations.

Keras is a high-level neural networks API that provides a user-friendly interface for building and training deep learning models. It abstracts away many low-level details, making it easy for beginners to create and experiment with neural networks. It is well-integrated with popular deep learning backends, especially TensorFlow, and offers flexibility in model design through both Sequential and Functional model APIs. Keras seamlessly works with NumPy arrays. You typically preprocess your data using NumPy, and Keras models accept NumPy arrays as input. You create the model architecture, compile it, and then feed data through the model. Known for its simplicity and user-friendly design, Keras provides a high-level API that abstracts many details, making it accessible for beginners.

PyTorch uses its own data structure called tensors. While it's possible to convert between NumPy arrays and PyTorch tensors, PyTorch tensors are the native data type. PyTorch uses dynamic computational graphs. This means the graph is built on-the-fly as operations are executed. This can be advantageous in certain scenarios, especially for dynamic and varying input sizes. PyTorch is designed to be more explicit, giving users more control over the details of their models. This can be advantageous for researchers and developers who need flexibility.

PyTorch is often used in research-oriented environments, while Keras is more commonly applied in practical settings. Generally, if you want to become a data scientist, it's recommended to learn PyTorch. On the other hand, if you aim to become a data analyst or engineer, learning Keras can be beneficial. Of course this is my personal opinion and not the absolute truth.

In the rest of this section, we will first start to get familiar with both of the libraries. We then demonstrate various examples of neural networks (NN), convolutional neural networks (CNN), and graph neural networks (GNN) using both Keras and PyTorch. Through these examples, you will gain insights into the advantages of each framework and be better able to determine which one aligns more with your preferences. Of course, this is not intended to be an exhaustive or real-world application; rather, it's meant for you to have fun with and explore the libraries.

### First steps

Let us start with the basics. For this I will start with a simulated Logit and then give a classification example on the famous Iris dataset.

#### Keras

In [ ]:
!pip install keras
!python -m pip install --upgrade pip
!pip install tensorflow

In [2]:
import os
# Keras works with 3 different backend as of Keras 3.0: jax, tensorflow, pytorch
os.environ["KERAS_BACKEND"] = "tensorflow"
import keras
keras.__version__

'3.0.5'

In [7]:
# Logit

import numpy as np
from keras.models import Sequential
from keras.layers import Dense

# Generate some sample data in numpy, the perfered data structure of Keras.
np.random.seed(0)
X = 2 * np.random.rand(1000, 13) # X is of dimension (1000,13) with values between 0-2
y = (np.random.rand(1000, 1)>0.5).astype(int) # y of dimension (1000,1) value 0 or 1

# Create a Keras sequential model
def create_model(input_dim):

    model = Sequential()

    # Add a single Dense layer with input dim 13 = number of features and output a single neuron 
    # Sigmoid activation function 
    model.add(Dense(units=1, input_dim=input_dim, activation='sigmoid'))

    # Parameter of optimization
    model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

    return model

# Train the model
model = create_model(13)
model.fit(X, y, epochs=1000, verbose=0)

# Make predictions
predictions = model.predict(X)

# Display the loss and accuracy
loss, accuracy = model.evaluate(X, y)
print("Loss:", loss)
print("Accuracy:", accuracy)

# Display the learned parameters
weights, bias = model.layers[0].get_weights()


print("Learned Weights:", weights)
print("Learned Bias:", bias)


32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - accuracy: 0.5613 - loss: 0.6859
Loss: 0.6880548000335693
Accuracy: 0.5450000166893005
Learned Weights: [[-0.02999177]
 [ 0.06566735]
 [ 0.12366135]
 [-0.02722669]
 [ 0.20459336]
 [-0.10692663]
 [-0.01676666]
 [-0.10032698]
 [ 0.00637742]
 [-0.13347614]
 [ 0.01018549]
 [-0.0195969 ]
 [-0.10994846]]
Learned Bias: [0.14966391]


In [47]:
# The same but with iris

import numpy as np
import pandas as pd
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv("G:/Github/Advanced_programming/data/Chap5/iris.csv")
X = df.iloc[:,0:4].values
y = df.iloc[:,4:5].values

# This time the target value is categorical. We need to one-hot encode it.
enc = OneHotEncoder()
y_encoded = enc.fit_transform(y).toarray()

# Create a Keras sequential model
def create_model(input_dim, output_dim):

    model = Sequential()

    # Add a single Dense layer with input dim 13 = number of features and output a single neuron 
    # Sigmoid activation function 
    model.add(Dense(units=output_dim, input_dim=input_dim, activation='sigmoid'))

    # Parameter of optimization
    model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

    return model

# Train the model
model = create_model(X.shape[1],y_encoded.shape[1])
model.fit(X, y_encoded, epochs=1000, verbose=0)

# Make predictions
predictions = model.predict(X)

# Display the loss and accuracy
loss, accuracy = model.evaluate(X, y_encoded)
print("Loss:", loss)
print("Accuracy:", accuracy)

# Display the learned parameters
weights, bias = model.layers[0].get_weights()


print("Learned Weights:", weights)
print("Learned Bias:", bias)


d:\anaconda3\envs\ap\Lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9842 - loss: 0.1315 
Loss: 0.17954681813716888
Accuracy: 0.9800000190734863
Learned Weights: [[ 1.4497296   1.1178024  -0.949229  ]
 [ 0.81996244 -0.7238664  -1.6423622 ]
 [-2.6269233  -0.59547603  2.0923035 ]
 [-1.1622708  -0.07232351  2.0126088 ]]
Learned Bias: [ 0.29411888  0.34348464 -0.6376028 ]


#### Pytorch

In [ ]:
!pip install torch

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim

# Generate some sample data directly using PyTorch
torch.manual_seed(0)
X = 2 * torch.rand((1000, 13))  # X is of dimension (1000, 13) with values between 0-2
y = (torch.rand((1000, 1)) > 0.5).float()  # y of dimension (1000, 1) with values 0 or 1

# Define the logistic regression model in PyTorch
class LogisticRegressionModel(nn.Module):
    def __init__(self):
        super(LogisticRegressionModel, self).__init__()
        self.linear = nn.Linear(13, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.linear(x)
        x = self.sigmoid(x)
        return x

# Instantiate the model, loss function, and optimizer
model = LogisticRegressionModel()
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Train the model
num_epochs = 1000
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, y)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# Make predictions on the training set
with torch.no_grad():
    predictions = model(X)

# Display the loss and accuracy
loss = criterion(predictions, y)
accuracy = ((predictions > 0.5).float() == y).float().mean().item()

print("Loss:", loss.item())
print("Accuracy:", accuracy)

# Display the learned parameters
learned_weights = model.linear.weight.data.numpy()
learned_bias = model.linear.bias.data.numpy()

print("Learned Weights:", learned_weights)
print("Learned Bias:", learned_bias)

Loss: 0.6926108598709106
Accuracy: 0.5199999809265137
Learned Weights: [[ 0.02706285  0.05788565  0.0088839   0.03678624 -0.06637889 -0.10481282
  -0.07036275  0.1973196   0.04217785 -0.08689839  0.02863655 -0.08786355
   0.03931884]]
Learned Bias: [-0.00564162]


In [77]:
import torch
import pandas as pd
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder

# Load the Iris dataset
df = pd.read_csv("G:/Github/Advanced_programming/data/Chap5/iris.csv")
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4:5].values

# Use OneHotEncoder for one-hot encoding
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Convert to PyTorch tensors
X_tensor = torch.FloatTensor(X)
y_tensor = torch.LongTensor(y_encoded)  # Use LongTensor for class indices

# Define the multi-class classification model in PyTorch
class SoftmaxRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(SoftmaxRegression, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
    
    def forward(self, x):
        return self.linear(x)
    
# Instantiate the model, loss function, and optimizer
model = SoftmaxRegression(X.shape[1], len(label_encoder.classes_))
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Train the model
num_epochs = 1000
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_tensor)
    loss = criterion(outputs, y_tensor)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# Make predictions on the training set
with torch.no_grad():
    predictions = model(X_tensor).argmax(dim=1)

# Display the loss and accuracy
accuracy = (predictions == y_tensor).float().mean().item()

print("Loss:", loss.item())
print("Accuracy:", accuracy)

# Display the learned parameters
learned_weights = model.linear.weight.data.numpy()
learned_bias = model.linear.bias.data.numpy()

print("Learned Weights:", learned_weights)
print("Learned Bias:", learned_bias)


d:\anaconda3\envs\ap\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Loss: 0.3437958359718323
Accuracy: 0.9599999785423279
Learned Weights: [[ 0.584271    1.2367085  -1.4465144  -0.16792874]
 [ 0.33822206  0.00474036  0.28807935 -0.558156  ]
 [-0.29904243 -0.11848312  0.8245503   0.9773022 ]]
Learned Bias: [-0.3053165   0.18019998 -0.509855  ]


: 

### Basic ANN

In the next examples we will only work with simulated data. The extension from a Logit to a Deep Neural Network is straightforward: add layers. If you want to read more about the maths behind you can go to https://github.com/Kwirtz/Masters-thesis

#### Keras

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

# Generate some sample data in numpy, the perfered data structure of Keras.
np.random.seed(0)
X = 2 * np.random.rand(1000, 13) # X is of dimension (1000,13) with values between 0-2
y = (np.random.rand(1000, 1)>0.5).astype(int) # y of dimension (1000,1) value 0 or 1

# Create a Keras sequential model
def create_model(input_dim):

    model = Sequential()

    model.add(Dense(units=6, input_dim=input_dim, activation='relu'))
    model.add(Dense(units=3, input_dim=6, activation='tanh'))
    model.add(Dense(units=1, input_dim=3, activation='sigmoid'))

    # Parameter of optimization
    model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

    return model

# Train the model
model = create_model(13)
model.fit(X, y, epochs=1000, verbose=0)

# Make predictions
predictions = model.predict(X)

# Display the loss and accuracy
loss, accuracy = model.evaluate(X, y)
print("Loss:", loss)
print("Accuracy:", accuracy)

# Display the learned parameters
weights, bias = model.layers[0].get_weights()


print("Learned Weights:", weights)
print("Learned Bias:", bias)

d:\anaconda3\envs\ap\Lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.5796 - loss: 0.6748
Loss: 0.6750162839889526
Accuracy: 0.5740000009536743
Learned Weights: [[-0.4196801   0.00680731  0.1597391  -0.3605326   0.78662187 -0.7330399 ]
 [-0.25520197  0.30476987  0.15540582  0.3816981  -0.28491476 -0.19996245]
 [-0.3662898  -0.00177413  0.39288893 -0.37944707  0.5912493   0.17201051]
 [ 0.49356464 -0.02677529  0.124106   -0.1027741   0.63024676 -0.38500684]
 [-0.06351601  0.17742766  0.71370953  0.51008147 -0.08762832  0.18800147]
 [ 0.08288312  0.16383585 -0.1735739  -0.04432764 -0.52658564 -0.41826892]
 [ 0.3629843   0.19836167  0.10548487 -0.43004385  0.4467683  -0.33218703]
 [-0.00850612  0.28580937 -0.07770222  0.13697319 -0.4945716  -0.5668438 ]
 [-0.37907127 -0.14924575  0.12196314  0.28334576 -0.2120233  -0.33470097]
 [ 0.24744192 -0.88164234 -0.25995627 -0.46744072 -0.13421354  0.3023705 ]
 [-0.38520855  0.20971037  0.3745023  -0.06832974  0.25311705  0

#### Pytorch

In [5]:
import torch
import torch.nn as nn
import torch.optim as optim

# Generate some sample data directly using PyTorch
torch.manual_seed(0)
X = 2 * torch.rand((1000, 13))  # X is of dimension (1000, 13) with values between 0-2
y = (torch.rand((1000, 1)) > 0.5).float()  # y of dimension (1000, 1) with values 0 or 1

# Define the Artificial Neural Network model in PyTorch
class NeuralNetworkModel(nn.Module):
    def __init__(self, input_dim):
        super(NeuralNetworkModel, self).__init__()
        self.layer1 = nn.Linear(input_dim, 6)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(6, 3)
        self.tanh = nn.Tanh()
        self.layer3 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        x = self.tanh(x)
        x = self.layer3(x)
        x = self.sigmoid(x)
        return x

# Instantiate the model, loss function, and optimizer
model = NeuralNetworkModel(input_dim=13)
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Train the model
num_epochs = 1000
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, y)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# Make predictions on the training set
with torch.no_grad():
    predictions = model(X)

# Display the loss and accuracy
loss = criterion(predictions, y)
accuracy = ((predictions > 0.5).float() == y).float().mean().item()

print("Loss:", loss.item())
print("Accuracy:", accuracy)

# Display the learned parameters
learned_weights_hidden = model.layer1.weight.data.numpy()
learned_bias_hidden = model.layer1.bias.data.numpy()
learned_weights_output = model.layer3.weight.data.numpy()
learned_bias_output = model.layer3.bias.data.numpy()

print("Learned Weights (Hidden Layer):", learned_weights_hidden)
print("Learned Bias (Hidden Layer):", learned_bias_hidden)
print("Learned Weights (Output Layer):", learned_weights_output)
print("Learned Bias (Output Layer):", learned_bias_output)


Loss: 0.6912749409675598
Accuracy: 0.5429999828338623
Learned Weights (Hidden Layer): [[ 0.27676916  0.22004108 -0.01971278 -0.17247663 -0.15132871 -0.08123114
  -0.22645132  0.27516913  0.00834347 -0.26574063 -0.13962209 -0.0897949
  -0.22472286]
 [-0.05971444 -0.17539938 -0.07008361 -0.2085401  -0.00351137 -0.18862922
   0.11213145  0.06330274 -0.02105505  0.16538756  0.13970141 -0.01688642
   0.00141582]
 [ 0.10929148 -0.23835024  0.05312441  0.02026546 -0.00936524 -0.07474421
  -0.13400179  0.08516776 -0.19301999  0.10432585 -0.22973296  0.07563709
   0.02641906]
 [-0.14505142 -0.13391112 -0.08370666 -0.13641164 -0.08411308 -0.07115243
   0.2067233   0.00343365  0.22648242 -0.06908101 -0.22084124 -0.07287527
   0.13551839]
 [-0.20449051  0.22203276 -0.01413966  0.23885901 -0.05770554 -0.23124187
  -0.149548    0.04953567 -0.1916856   0.25017902  0.25512478 -0.06451254
   0.2108624 ]
 [ 0.08420499 -0.02861391 -0.27390605 -0.2299333  -0.21122538 -0.02463877
   0.2118786   0.07191713 

### Basic CNN

#### Keras

In [6]:
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from keras.optimizers import Adam

# Generate random images for training
num_samples = 1000
image_size = (64, 64, 3)  # Assuming RGB images

# Randomly generate images
X_train = np.random.rand(num_samples, *image_size)
y_train = np.random.randint(2, size=num_samples)

# Define the CNN model
model = Sequential()

# Convolutional layer with 32 filters, kernel size 3x3, and ReLU activation
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=image_size))
# Max pooling layer with pool size 2x2
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

# Flatten layer to transition from convolutional layers to fully connected layers
model.add(Flatten())

# Fully connected layer with 128 neurons and ReLU activation
model.add(Dense(128, activation='relu'))

# Output layer with 1 neuron and sigmoid activation for binary classification
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)


d:\anaconda3\envs\ap\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - accuracy: 0.5303 - loss: 0.8553
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.5086 - loss: 0.6942
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.5359 - loss: 0.6927
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.5719 - loss: 0.6922
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.5009 - loss: 0.6927
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.6064 - loss: 0.6903
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.5424 - loss: 0.6884
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.5221 - loss: 0.6916
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.5323 - loss: 0.6941
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.5523 - loss: 0.6917


#### Pytorch

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Set random seed for reproducibility
torch.manual_seed(0)

# Generate random images for training
num_samples = 1000
image_size = (3, 64, 64)  # Assuming RGB images

# Randomly generate images
X_train = torch.rand(num_samples, *image_size)
y_train = torch.randint(2, size=(num_samples,))

# Define the CNN model
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(64 * 16 * 16, 128)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(128, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.conv1(x)
        x = self.relu(x)
        x = self.pool1(x)
        x = self.conv2(x)
        x = self.relu(x)
        x = self.pool2(x)
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.sigmoid(x)
        return x

# Instantiate the model
model = SimpleCNN()

# Define the loss function and optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Train the model
num_epochs = 10
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs, y_train.float().view(-1, 1))

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# You can now use the trained model to make predictions on new data

### Basic RNN

#### Keras

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense

# Generate some sample data directly using NumPy
np.random.seed(0)
seq_length = 10
num_samples = 1000

X_train = np.random.randn(num_samples, seq_length, 1)
y_train = np.sum(X_train, axis=1)

# Define the RNN model
model = Sequential()

# Add a SimpleRNN layer with 32 units and tanh activation
model.add(SimpleRNN(32, activation='tanh', input_shape=(seq_length, 1)))

# Add a Dense layer with one unit for regression
model.add(Dense(1))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Print the model summary
model.summary()

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)

#### Pytorch

In [8]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Set random seed for reproducibility
torch.manual_seed(0)

# Generate some sample data directly using NumPy
np.random.seed(0)
seq_length = 10
num_samples = 1000

X_train = np.random.randn(num_samples, seq_length, 1).astype(np.float32)
y_train = np.sum(X_train, axis=1).astype(np.float32)

# Convert NumPy arrays to PyTorch tensors
X_train_tensor = torch.from_numpy(X_train)
y_train_tensor = torch.from_numpy(y_train)

# Define the RNN model
class SimpleRNNModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleRNNModel, self).__init__()
        self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, _ = self.rnn(x)
        out = self.fc(out[:, -1, :])  # Take the output from the last time step
        return out

# Instantiate the model
input_size = 1
hidden_size = 32
output_size = 1
model = SimpleRNNModel(input_size, hidden_size, output_size)

# Define the loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Print the model summary
print(model)

# Train the model
num_epochs = 10
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# You can now use the trained model to make predictions on new data


SimpleRNNModel(
  (rnn): RNN(1, 32, batch_first=True)
  (fc): Linear(in_features=32, out_features=1, bias=True)
)


### Basic GNN

In [9]:
!pip install torch_geometric
!pip install stellargraph

  Using cached torch_geometric-2.5.0-py3-none-any.whl.metadata (64 kB)
  Using cached tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
  Using cached aiohttp-3.9.3-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
  Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl.metadata (12 kB)
  Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl.metadata (4.3 kB)
  Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl.metadata (32 kB)
Using cached torch_geometric-2.5.0-py3-none-any.whl (1.1 MB)
Using cached aiohttp-3.9.3-cp312-cp312-win_amd64.whl (363 kB)
   ---------------------------------------- 0.0/103.2 kB ? eta -:--:--
   ----------- --------------------------- 30.7/103.2 kB 660.6 kB/s eta 0:00:01
   ---------------------------------------  102.4/103.2 kB 1.5 MB/s eta 0:00:01
   ---------------------------------------  102.4/103.2 kB 1.5 MB/s eta 0:00:01
   ----------

ERROR: Ignored the following versions that require a different python version: 0.10.0 Requires-Python >=3.6.0, <3.8.0; 0.11.0 Requires-Python >=3.6.0, <3.8.0; 0.11.1 Requires-Python >=3.6.0, <3.8.0; 0.4.0 Requires-Python >=3.6,<3.7; 0.4.0b0 Requires-Python >=3.6,<3.7; 0.4.1 Requires-Python >=3.5.0, <3.7.0; 0.5.0 Requires-Python >=3.5.0, <3.7.0; 0.6.0 Requires-Python >=3.5.0, <3.7.0; 0.6.1 Requires-Python >=3.5.0, <3.7.0; 0.7.0 Requires-Python >=3.5.0, <3.8.0; 0.7.1 Requires-Python >=3.5.0, <3.8.0; 0.7.2 Requires-Python >=3.5.0, <3.8.0; 0.7.3 Requires-Python >=3.5.0, <3.8.0; 0.8.0 Requires-Python >=3.5.0, <3.8.0; 0.8.1 Requires-Python >=3.5.0, <3.8.0; 0.8.2 Requires-Python >=3.5.0, <3.8.0; 0.8.3 Requires-Python >=3.5.0, <3.8.0; 0.8.4 Requires-Python >=3.5.0, <3.8.0; 0.9.0 Requires-Python >=3.6.0, <3.8.0; 1.0.0 Requires-Python >=3.6.0, <3.8.0; 1.0.0rc1 Requires-Python >=3.6.0, <3.8.0; 1.1.0 Requires-Python >=3.6.0, <3.9.0; 1.2.0 Requires-Python >=3.6.0, <3.9.0; 1.2.1 Requires-Python >=3.

#### Keras

In [ ]:
import numpy as np
import networkx as nx
from stellargraph import StellarGraph
from stellargraph.layer import GraphConvolution
from keras import layers, Model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Generate the Karate Club graph
graph = nx.karate_club_graph()

# Node features (randomly initialized for illustration purposes)
feature_size = 16
node_features = np.random.randn(len(graph.nodes), feature_size)

# Labels (1 for "Mr. Hi" club, 0 for "John A" club)
labels = np.array([1 if graph.nodes[node]["club"] == "Mr. Hi" else 0 for node in graph.nodes])

# Create a StellarGraph object
G = StellarGraph(features=node_features, edges=graph.edges())

# Split the data into training and testing sets
train_nodes, test_nodes = train_test_split(G.nodes(), test_size=0.2, random_state=42)

train_targets = labels[train_nodes]
test_targets = labels[test_nodes]

# Convert labels to one-hot encoding
target_encoder = LabelEncoder()
train_targets = target_encoder.fit_transform(train_targets)
test_targets = target_encoder.transform(test_targets)

# Define the graph convolutional network (GCN) model using Keras
gcn = GraphConvolution(layer_sizes=[hidden_dim, output_dim], activations=["relu", "softmax"], generator=G)
x_input, x_output = gcn.in_out_tensors()

# Create the Keras model
model = Model(inputs=x_input, outputs=x_output)

# Compile the model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

# Train the model
epochs = 100
history = model.fit(
    generator.flow(train_nodes, train_targets),
    epochs=epochs,
    validation_data=generator.flow(test_nodes, test_targets),
)

# Evaluate the model
test_metrics = model.evaluate(generator.flow(test_nodes, test_targets))
print("\nTest Set Metrics:")
for name, val in zip(model.metrics_names, test_metrics):
    print("\t{}: {:0.4f}".format(name, val))


#### Pytorch

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GraphConv
from torch_geometric.utils import karate_club_graph
from torch.nn.functional import binary_cross_entropy_with_logits

# Generate the Karate Club graph
edge_index, _ = karate_club_graph()

# Node features (randomly initialized for illustration purposes)
num_nodes = edge_index.max().item() + 1
x = torch.randn(num_nodes, 16)

# Labels (1 for "Mr. Hi" club, 0 for "John A" club)
y = torch.tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Create a PyTorch Geometric Data object
data = Data(x=x, edge_index=edge_index, y=y)

# Define the Graph Neural Network model
class GNNModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(GNNModel, self).__init__()
        self.conv1 = GraphConv(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.conv2 = GraphConv(hidden_dim, output_dim)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = self.relu(x)
        x = self.conv2(x, edge_index)
        return x

# Instantiate the model
input_dim = 16
hidden_dim = 32
output_dim = 1
model = GNNModel(input_dim, hidden_dim, output_dim)

# Define the loss function and optimizer
criterion = binary_cross_entropy_with_logits
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Train the model
num_epochs = 100
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(data)
    loss = criterion(outputs.view(-1), data.y.float())

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# You can now use the trained model to make predictions on new data


ImportError: cannot import name 'karate_club_graph' from 'torch_geometric.utils' (d:\anaconda3\envs\ap\Lib\site-packages\torch_geometric\utils\__init__.py)

In [2]:
import networkx as nx

G = nx.karate_club_graph()

In [6]:
print(G)

Graph named "Zachary's Karate Club" with 34 nodes and 78 edges


: 


<a name="PowerBI"></a>
## Power BI

Power BI, developed by Microsoft, is a business analytics tool that enables users to visualize and share insights from their data. It provides a suite of tools for data analysis, interactive reporting, and sharing of insights across an organization or embedding them in an app or website. Here are some key components and features of Power BI:

1. **Data Connectivity:** Power BI can connect to a wide variety of data sources, both on-premises and in the cloud. It supports connections to databases, spreadsheets, online services, and more. Popular data sources include Microsoft Excel, SQL Server, Azure services, SharePoint, and many third-party applications.

2. **Data Transformation and Modeling:** Power BI allows users to transform and shape their data using a graphical interface. This includes cleaning, filtering, and transforming data to make it suitable for analysis. Power BI also supports data modeling, allowing users to create relationships between different data tables.

3. **Visualization:** One of the key strengths of Power BI is its ability to create compelling visualizations. Users can build interactive reports and dashboards using a drag-and-drop interface. The tool provides a wide range of visualization options, including charts, graphs, maps, and tables.

4. **Data Analysis Expressions (DAX):** Power BI uses a formula language called Data Analysis Expressions (DAX) for creating custom calculations and aggregations. DAX is similar to Excel formulas and allows users to define complex calculations for their data.

5. **Power Query:** Power BI includes a data connectivity and preparation tool called Power Query. It allows users to connect, import, and transform data from various sources before loading it into Power BI.

6. **Power BI Service:** The Power BI Service is a cloud-based platform for sharing, collaborating, and publishing Power BI reports and dashboards. Users can publish their reports to the Power BI Service, making them accessible to others within or outside their organization.

7. **Power BI Desktop:** Power BI Desktop is a free, standalone application that allows users to create reports and dashboards on their local machines before publishing them to the Power BI Service.

8. **Power BI Mobile:** Power BI offers mobile apps for iOS and Android devices, allowing users to access and interact with their reports and dashboards on the go.

Overall, Power BI is a powerful tool for turning raw data into meaningful insights, making it a popular choice for businesses and analysts looking to visualize and analyze their data effectively.

<a name="PreviousProject"></a>
## Previous Project

Each year student tend to cluster around a topic (Scrapping, Dashboards, Apps, Computer vision, ...)

- Open cv + tensorflow to detect face using webcam and control pc
- News - buzzword - map
- Sentiment analysis on glassdoor
- Discord bot to connect on spotify and linked with youtube
- F1 dashboard
- mtse = research advanced
- Detect country of plate
- Finance bot following trending and selling with different strategy
- Table tennis
- Bot hearthstone (expert system)
- Se loger.com
- jvc + Linkedin
- Yuka like
- Recipe proposal
- Grocery shopping list preparation and price comparison