# Introduction.

This notebook is made to go through the fundamentals. You should already know all of this and if you don't now is the time ! I'm not gonna dive in basic operations (+,\**,%,...), control flow statements like if else and for and while loops and built-in types (int,float).  We will discuss more the bytes and ram usage in advanced concept section 

## Built-in types

Here are the built-in types in python https://www.informit.com/articles/article.aspx?p=453682&seqNum=5. Not going into much details for str and int just beware of the built-in number types when working with python. Most libraries use some kind of inference to define automatically the built-in types (if NaN in pandas dataframe => float) and it might lead to inneficient ram usage. If you want an idea of which int type to use depending on your data check here https://numpy.org/doc/stable/user/basics.types.html. (For example RGB = [0-255] uint8 seems like the best type for images.)


## Built-in data structures

A good understanding of built-in data structures is imperative to feel comfortable in Python. Next is a reminder of how to use the most prominent data structures.

### List

Lists are a mutable built-in data type in python that can stores multiples item from any built-in data type and any built-in types (int,float,...). 



In [22]:
# init list
x = [1,2,3,4,5]
print(x)


# slicing
first_position = x[0]
print("first_position",first_position)

last_position = x[-1]
print("last_position",last_position)

interval_position = x[0:2]
print("interval_position",interval_position)

## mutable part

# add object
x.append([3])
print("appended",x)
# remove object
x.remove([3])
print("removed",x)

x[0] = 10
print(x)
print(dir(x))

[1, 2, 3, 4, 5]
first_position 1
last_position 5
interval_position [1, 2]
appended [1, 2, 3, 4, 5, [3]]
removed [1, 2, 3, 4, 5]
[10, 2, 3, 4, 5]
['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


### Tuples

Tuples are just like list except they are immutable

In [1]:
x = (1,2,3,4,5)
print(x)

# slicing
first_position = x[0]
print("first_position",first_position)

last_position = x[-1]
print("last_position",last_position)

interval_position = x[0:2]
print("interval_position",interval_position)

# Misc
print("Where is 2 ?", x.index(2))
print(dir(x))

#immutable

#x[0] = 10

#  cant append or change value but you can still create a new variable building on a previous one
print(id(x))
x += x
print(x)
print(id(x))

(1, 2, 3, 4, 5)
first_position 1
last_position 5
interval_position (1, 2)
Where is 2 ? 1
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
2538998689120
(1, 2, 3, 4, 5, 1, 2, 3, 4, 5)
2538999328960


### Dict

A dictionary is a collection which can be ordered (depending on your python version), read more about order in dict: [1](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6),[2](https://gandenberger.org/2018/03/10/ordered-dicts-vs-ordereddict/),[3](https://medium.com/junior-dev/python-dictionaries-are-ordered-now-but-how-and-why-5d5a40ee327f). It is mutable and does not allow duplicates.

In [3]:
# {key:value} key must be a str, avoid special characters, value can be any python object
x = {"First name": "Kevin",
    "Last name": "Wirtz",
    "Lecture": "Advanced Programming"}
print(x)

# mutable
x.update({"First name": "other"})
print(x)

print(dir(x))

{'First name': 'Kevin', 'Last name': 'Wirtz', 'Lecture': 'Advanced Programming'}
{'First name': 'other', 'Last name': 'Wirtz', 'Lecture': 'Advanced Programming'}
['__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


### Set

A set unordered, unindexed and contains only unique elements, it is immutable but you can add and remove elements (unlikle tuples). Sets can't contain a list or a dict since they are mutable but it can contain a tuple.

In [12]:
myset = {1,3,2,3,(1,2,3),(1,2,3),4}
print(myset)

myset.update([10,(1,2,3)])
print(myset)
print(dir(myset))

{1, 2, 3, 4, (1, 2, 3)}
{1, 2, 3, 4, 10, (1, 2, 3)}
['__and__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


## Useful libraries

### Numpy
Numpy is the library of choice when working on arrays in Python, Why: 
- NumPy is written in C = it's fast. 
- Compatible with different libraries and specifically machine learning libraries.
- Built-in functions (random array for example)
- Universal functions that allows vectorization ( apply a function to every element instead of iterating through each one)

In [30]:
import numpy as np

# Basic operation

x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(x.shape)

y = np.array([[4,8,1,2,4,10,13,12,11]])
y = y.reshape((3,3))
print(y)
print(y.shape)

#addition
print(x+y)

# substraction
print(x-y)

# dot product
print(np.matmul(x,y))

# Hadamard product
print(np.multiply(x,y))

# Division
print(np.matmul(x,np.linalg.inv(y)))

# Hadamard division
print(np.divide(x,y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[ 4  8  1]
 [ 2  4 10]
 [13 12 11]]
(3, 3)
[[ 5 10  4]
 [ 6  9 16]
 [20 20 20]]
[[-3 -6  2]
 [ 2  1 -4]
 [-6 -4 -2]]
[[ 47  52  54]
 [104 124 120]
 [161 196 186]]
[[ 4 16  3]
 [ 8 20 60]
 [91 96 99]]
[[ 1.05263158e-01  2.89473684e-01 -2.77555756e-17]
 [ 1.27819549e-01  3.51503759e-01  2.14285714e-01]
 [ 1.50375940e-01  4.13533835e-01  4.28571429e-01]]
[[0.25       0.25       3.        ]
 [2.         1.25       0.6       ]
 [0.53846154 0.66666667 0.81818182]]


Ram efficiency is really important to take into consideration wen scaling up your application. To understand a bit more about numpy and space occupied by a numpy object you need to understand the concept of Strides

In [34]:
# Ram efficiency

x = np.zeros(shape=(4,4), dtype=np.int32)
print(repr(x))
print(x.dtype)
print(x.shape)
# reminder 8 bits = 1 byte
# Stride[0] = number of bytes to go from 1 array to an other
# Stride[1] = number of bytes to go from an element of an array to another one
# int32 = 32 bits = 4 bytes

print(x.strides)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)
int64
(4, 4)
(32, 8)


Imagine now a squared matrix 100000x100000 in int64 vs int8

In [39]:
print("in int 64 takes ",100000**2*8*10**-9, "GB of ram")
print("in int 8 takes ",100000**2*1*10**-9, "GB of ram")

in int 64 takes  80.0 GB of ram
in int 8 takes  10.0 GB of ram


This does not mean that you need to use int8 everywhere (reminder int8 ranges between -128 to 127) but don't let the automatic float64 everytime, think of your problem and matrix. 

Another way to manage ram issue is using sparse matrix. Sparse matrix are used when you have a matrix with a lot of 0's.

In [57]:
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import inv
import numpy as np
x = csr_matrix([[1, 2, 20], [0, 0, 3], [4, 0, 5]])
print("x: \n", x)

y = csr_matrix([[1, 2, 2, 0, 0, 3, 4, 0, 5]])
y = y.reshape((3,3))
print("y: \n", y)

print("x+y: \n",x+y)
print("x*y: \n",x.dot(y))
print("x/y: \n",x.dot(inv(y)))
print("x/y: \n",x._divide(y))

x: 
   (0, 0)	1
  (0, 1)	2
  (0, 2)	20
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
y: 
   (0, 0)	1
  (0, 1)	2
  (0, 2)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
x+y: 
   (0, 0)	2
  (0, 1)	4
  (0, 2)	22
  (1, 2)	6
  (2, 0)	8
  (2, 2)	10
x*y: 
   (0, 2)	108
  (0, 1)	2
  (0, 0)	81
  (1, 2)	15
  (1, 0)	12
  (2, 2)	33
  (2, 1)	8
  (2, 0)	24
x/y: 
   (0, 0)	1.0
  (0, 1)	5.999999999999999
  (1, 1)	1.0
  (2, 2)	1.0
x/y: 
   (0, 0)	1
  (0, 1)	1
  (0, 2)	10
  (1, 2)	1
  (2, 0)	1
  (2, 2)	1


In [59]:
#size comparison
import sys
from scipy.sparse import csr_matrix
import numpy as np
x = csr_matrix((25000, 25000), dtype = np.int8)
y = np.zeros((25000, 25000), dtype = np.int8)
print("size of sparse in bytes :",sys.getsizeof(x))
print("size of numpy in bytes :",sys.getsizeof(y))

size of sparse in bytes : 48
size of numpy in bytes : 625000112


Another option is numpy memmap. Instead of using the ram it uses the disk space to store the numpy object.

In [ ]:
import numpy as np

nrows, ncols = 1000000, 100

f = np.memmap('memmapped.dat', dtype=np.float32,
              mode='w+', shape=(nrows, ncols))

for i in range(ncols):
    f[:, i] = np.random.rand(nrows)
    
x = f[:, -1]

del f

### Pandas


### Matplotlib

## Know your machine

![friends](img/know_your_machine.png)